@host=http://localhost:5000

###
GET {{host}}/api/users HTTP/1.1

###
POST {{host}}/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "docker da massa",
    "email": "dockernerizarado@email.com",
    "password": "docker na lagoa"
}