@host=http://localhost:3000

###
GET {{host}}/api/users HTTP/1.1

###
GET {{host}}/api/users/27 HTTP/1.1

### busca usuários Felipe que usam gmail
GET {{host}}/api/users?email=gmail&name=Felipe HTTP/1.1

###
POST {{host}}/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Felipe",
    "email": "felipe@gmail.com",
    "password": "123321"
}